[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "https://vinh-dev.netlify.app/*"
  to = "https://vinh.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
